/**
 * Generates config.mjs files for both Lambda@Edge functions by baking environment
 * variable values into static JavaScript modules.
 *
 * Lambda@Edge does not support environment variables at runtime, so configuration
 * must be embedded at build time. Run this script before `sam build`.
 *
 * Usage:
 *   node scripts/build-config.mjs
 *
 * Reads from (in priority order):
 *   1. Existing process environment
 *   2. .env file in the project root
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

function loadDotenv() {
  try {
    const envFile = readFileSync(resolve(ROOT, '.env'), 'utf-8');
    for (const line of envFile.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const value = trimmed.slice(eqIdx + 1).trim();
      if (key && !process.env[key]) {
        process.env[key] = value;
      }
    }
  } catch {
    // .env not present; rely on existing environment variables
  }
}

function required(name) {
  const val = process.env[name];
  if (!val || val.startsWith('__')) {
    throw new Error(
      `Required environment variable "${name}" is not set.\n` +
        `Copy .env.example to .env and fill in your values.`
    );
  }
  return val;
}

loadDotenv();

const callbackUrl = required('CALLBACK_URL');
// Derive logout URL from callback URL: strip /callback → site root
const logoutUrl = callbackUrl.replace(/\/callback$/, '');

const config = {
  region: required('AWS_REGION'),
  userPoolId: required('USER_POOL_ID'),
  clientId: required('CLIENT_ID'),
  cognitoDomain: required('COGNITO_DOMAIN'),
  callbackUrl,
  logoutUrl,
};

const content = `// Auto-generated by scripts/build-config.mjs — do not edit manually.
export const config = ${JSON.stringify(config, null, 2)};
`;

const targets = [
  resolve(ROOT, 'src/auth-check/config.mjs'),
  resolve(ROOT, 'src/auth-callback/config.mjs'),
];

for (const target of targets) {
  writeFileSync(target, content);
  process.stderr.write(`Generated: ${target}\n`);
}

process.stderr.write('\nConfig baked successfully. Run `sam build` next.\n');
